# Generated by Django 2.0.2 on 2018-02-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_autor', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_editorial', models.IntegerField()),
                ('nombre_editorial', models.CharField(max_length=100)),
                ('ciudad_editorial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genero', models.IntegerField()),
                ('nombre_genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_libro', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('prologo', models.TextField(max_length=500)),
                ('ciudad_publicacion', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('num_paginas', models.IntegerField()),
                ('traduccion', models.BooleanField()),
                ('titulo_traduccion', models.CharField(max_length=100)),
                ('codigo_isbn', models.CharField(max_length=10)),
                ('autor', models.ManyToManyField(blank=True, null=True, to='home.Autor')),
            ],
        ),
        migrations.AddField(
            model_name='genero',
            name='libro',
            field=models.ManyToManyField(blank=True, null=True, to='home.Libro'),
        ),
        migrations.AddField(
            model_name='editorial',
            name='libro',
            field=models.ManyToManyField(blank=True, null=True, to='home.Libro'),
        ),
    ]
