# Generated by Django 2.0.3 on 2018-03-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='id_autor',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='id_editorial',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='id_genero',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='id_libro',
        ),
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img_autor'),
        ),
        migrations.AddField(
            model_name='editorial',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img_editorial'),
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='img_libro'),
        ),
    ]
